name: Chart build and test 3.x

on:
  workflow_dispatch: {}
  # Normally using pull_request_target along with checking out the ref of the PR is not
  # a good idea, but this is low risk since it's a Helm chart repo.
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

  # Uncomment this if you need to actively test this workflow from a PR draft
  # pull_request:
  #   branches:
  #     - develop

# Prevents multiple runs of the same workflow on the same branch from executing
# simultaneously. Saves resources.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      # Lint all chart values including those in the ci directory.
      - name: Run chart-testing (lint)
        run: |
          helm repo add finops-agent-chart https://kubecost.github.io/finops-agent-chart
          helm repo add mcp-kubecost https://kubecost.github.io/mcp-kubecost
          helm repo update
          helm dependency build kubecost/
          ct lint --chart-dirs=kubecost/ --charts kubecost/ --validate-maintainers=false

      # Run `helm template` on the main values file plus all those in the ci directory.
      - name: Helm template
        run: |
          helm template kubecost/ -f .github/ci-helmValues/helmValues-federated-store.yaml > full.yaml
          directory="kubecost/ci"
          for file in "$directory"/*; do
          if [ -f "$file" ]; then
              echo "Templating file $file"
              helm template kubecost/ -f "$file" >> full.yaml
          fi
          done

      # Run Kubeconform on the combined, templatized output across all tested values stored in `full.yaml`.
      # Ensure all the rendered resources are valid.
      - name: Kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: /kubeconform
          args: "-summary -ignore-missing-schemas -output text full.yaml"

      - name: Frontend serverBlockConfig template tests
        run: |
          helm repo add mcp-kubecost https://kubecost.github.io/mcp-kubecost
          helm repo update
          helm dependency build kubecost/
          .github/scripts/extra_server_config_test.sh

  # Test cluster versions.
  deploy-chart:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - name: v1.36
            version: v1.36.4
    needs: test-chart
    name: ${{ matrix.k8s-version.name }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Create KinD cluster
        uses: helm/kind-action@06c1ae10762d3b9c1644e7fe69596ae519e015a2 #v1.15.0
        with:
          version: v0.31.0
          node_image: kindest/node:${{ matrix.k8s-version.version }}
          kubectl_version: ${{ matrix.k8s-version.version }}

      - name: Populate federated storage config secret
        run: |
          sed -i "s|FEDERATED_STORAGE_CONFIG_YAML|${{ secrets.FEDERATED_STORAGE_CONFIG_YAML }}|" .github/ci-files/federatedStorageConfigSecret.yaml

      # Create necessary test files in the cluster. Some configurations of the chart
      # require pre-existing files like Secrets in order for volume mounts to be valid. Without them,
      # Pods won't come up and tests will fail.
      - name: Create kubecost Namespace and test files
        run: |
          kubectl create ns kubecost
          kubectl -n kubecost create -f .github/ci-files

      # Install the chart with default values and check results.
      - name: Install Kubecost chart
        working-directory: ./kubecost
        run: |
          helm repo add finops-agent-chart https://kubecost.github.io/finops-agent-chart
          helm repo add mcp-kubecost https://kubecost.github.io/mcp-kubecost
          helm repo update
          helm dependency build
          helm install --wait --wait-for-jobs kubecost . -n kubecost

      - name: Wait for ready
        run: kubectl wait -n kubecost --for=condition=ready pod --selector app.kubernetes.io/instance=kubecost --timeout=120s

      - name: gather debug info - install
        if: failure()
        run: |
          kubectl get pods -n kubecost
          kubectl get pods -n kubecost -o yaml
          kubectl get pods -n kubecost -o json
          kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
          kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
          kubectl -n kubecost describe pods
          kubectl -n kubecost logs -l app.kubernetes.io/instance=kubecost

      - name: Run Helm tests
        run: helm test -n kubecost kubecost

      - name: gather debug info - test
        if: failure()
        run: |
          kubectl get pods -n kubecost
          kubectl get pods -n kubecost -o yaml
          kubectl get pods -n kubecost -o json
          kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
          kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
          kubectl -n kubecost describe pods
          echo "kubecost logs"
          kubectl -n kubecost logs -l app.kubernetes.io/instance=kubecost
          echo "agg logs"
          kubectl -n kubecost logs -l app.kubernetes.io/instance=aggregator
          echo "basic-health logs"
          kubectl -n kubecost logs basic-health

      - name: Uninstall chart
        run: helm uninstall kubecost -n kubecost --no-hooks --wait

      - name: Cleanup all Pods in Kubecost Namespace
        run: kubectl -n kubecost delete deployments,daemonsets,statefulsets,pods --all --force

      # Loops over all the other values files in the ci directory and installs the chart, runs Helm tests, and uninstalls.
      # Additional sleeps seem necessary for the main Kubecost Pod to be completely available, both frontend and backend.
      - name: Install, test, remove chart for other values
        id: loopingtests
        run: |
          directory="kubecost/ci"
          for file in "$directory"/*; do
          if [ -f "$file" ]; then
            echo "### Sleeping for 30 seconds ###"
            sleep 30
            echo "### Performing installation with values from $file ###"
            helm install --wait --wait-for-jobs kubecost kubecost/ -n kubecost -f "$file"
            echo "### Waiting for kubecost Pod readiness. ###"
            kubectl wait -n kubecost --for=condition=ready pod --selector app.kubernetes.io/instance=kubecost --timeout=120s
            echo "### [DEBUG] printing debug info ###"
            kubectl -n kubecost get pods
            kubectl get pods -n kubecost -o yaml
            kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
            kubectl get pods -n kubecost -o jsonpath='{.items[*].spec.containers[*].image}'
            kubectl -n kubecost describe pods
            kubectl -n kubecost logs -l app.kubernetes.io/instance=kubecost
            echo "### Performing helm tests ###"
            helm test -n kubecost $(helm ls -n kubecost --all --short)
            echo "### Performing uninstallation ###"
            helm uninstall $(helm ls -n kubecost --all --short) -n kubecost --no-hooks --wait
            echo "### Cleaning up all Pods and Pod controllers in Kubecost Namespace ###"
            kubectl -n kubecost delete deployments,daemonsets,statefulsets,pods --all --force
          fi
          done

      - name: Checkout Target Branch
        uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: ./target-branch

      - name: Install, Upgrade, Test, and Uninstall chart for default values
        run: |
          cd ./target-branch/kubecost
          helm repo add finops-agent-chart https://kubecost.github.io/finops-agent-chart
          helm repo add mcp-kubecost https://kubecost.github.io/mcp-kubecost
          helm repo update
          helm dependency build
          helm install --wait --wait-for-jobs kubecost . -n kubecost
          kubectl wait -n kubecost --for=condition=ready pod --selector app.kubernetes.io/instance=kubecost --timeout=120s
          cd ../..
          helm upgrade kubecost kubecost/ -n kubecost --wait --wait-for-jobs
          kubectl wait -n kubecost --for=condition=ready pod --selector app.kubernetes.io/instance=kubecost --timeout=120s
          helm test -n kubecost kubecost
          helm uninstall kubecost -n kubecost --no-hooks --wait
          kubectl -n kubecost delete deployments,daemonsets,statefulsets,pods --all --force


  deploy-ocp:
    runs-on: ubuntu-latest
    needs: test-chart
    strategy:
      matrix:
        cluster:
        - distribution: openshift
          version: 4.22.0-okd
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # Outputs: `cluster-kubeconfig`, `cluster-id`
      - name: Create Cluster
        id: create-cluster
        uses: replicatedhq/replicated-actions/create-cluster@v1.27.1
        with:
          kubernetes-distribution: ${{ matrix.cluster.distribution }}
          kubernetes-version: ${{ matrix.cluster.version }}
          cluster-name: ${{ matrix.cluster.distribution }}-${{ matrix.cluster.version }}
          timeout-minutes: 10
          ttl: 10m
          export-kubeconfig: true
          disk: 150
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}

      - name: Populate federated storage config secret
        run: |
          sed -i "s|FEDERATED_STORAGE_CONFIG_YAML|${{ secrets.FEDERATED_STORAGE_CONFIG_YAML }}|" .github/ci-files/federatedStorageConfigSecret.yaml

      - name: Create kubecost Namespace and test files
        run: |
          kubectl create ns kubecost
          kubectl -n kubecost create -f .github/ci-files

      # Install the chart with OCP values and check results.
      - name: Install Kubecost chart with OCP values
        working-directory: ./kubecost
        run: |
          helm repo add finops-agent-chart https://kubecost.github.io/finops-agent-chart
          helm repo add mcp-kubecost https://kubecost.github.io/mcp-kubecost
          helm repo update
          helm dependency build
          helm install --wait --wait-for-jobs kubecost . -n kubecost \
          -f values-openshift.yaml \
          --set networkCosts.enabled=true \
          --set clusterController.enabled=true \
          --set clusterController.storageConfigSecret=actions-bucket-config \
          --set-json 'networkCosts.affinity=null'

      - name: Wait for ready
        run: kubectl wait -n kubecost --for=condition=ready pod --selector app.kubernetes.io/instance=kubecost --timeout=120s
      - name: Run Helm tests
        run: helm test -n kubecost kubecost
      - name: Test — network-costs starts
        ## nodes do not have regions, no data expected. Just verify it starts:
        run: kubectl wait -n kubecost --for=condition=ready pod --selector app.kubernetes.io/name=network-costs --timeout=120s
      - name: Remove Cluster
        id: remove-cluster
        uses: replicatedhq/replicated-actions/remove-cluster@v1.27.1
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}

  deploy-eks:
    runs-on: ubuntu-latest
    needs: test-chart
    strategy:
      matrix:
        cluster:
        - distribution: eks
          version: v1.36
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Create Cluster
        id: create-cluster
        uses: replicatedhq/replicated-actions/create-cluster@v1.27.1
        with:
          kubernetes-distribution: ${{ matrix.cluster.distribution }}
          kubernetes-version: ${{ matrix.cluster.version }}
          cluster-name: ${{ matrix.cluster.distribution }}-${{ matrix.cluster.version }}
          timeout-minutes: 10
          ttl: 10m
          export-kubeconfig: true
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}

      - name: Create kubecost Namespace
        run: |
          kubectl create ns kubecost

      # replicated eks cluster do not set the storage class as default, so we need to do it manually
      - name: Set the storage class as default
        run: |
          kubectl patch storageclass gp2 -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

      # Install the chart with EKS values and check results.
      - name: Install Kubecost chart with EKS values
        working-directory: ./kubecost
        run: |
          helm repo add finops-agent-chart https://kubecost.github.io/finops-agent-chart
          helm repo add mcp-kubecost https://kubecost.github.io/mcp-kubecost
          helm repo update
          helm dependency build
          helm install --wait --wait-for-jobs kubecost . -n kubecost -f values-eks-cost-monitoring.yaml

      - name: Wait for ready
        run: kubectl wait -n kubecost --for=condition=ready pod --selector app.kubernetes.io/instance=kubecost --timeout=120s
      - name: Run Helm tests
        run: helm test -n kubecost kubecost
      - name: Test — network-costs
        run: kubectl wait -n kubecost --for=condition=ready pod --selector app.kubernetes.io/name=network-costs --timeout=120s
      - name: Remove Cluster
        id: remove-cluster
        uses: replicatedhq/replicated-actions/remove-cluster@v1.27.1
        continue-on-error: true
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}
